#!/usr/bin/env bash
# Displays numbers from 1 to 20 in addition to:
#   Display "bad luck from China" for the 4th line
#   Display "bad luck from Japan" for the 9th line
#   Display "bad luck from Italy" for the 17th line

iterator=1

while ((iterator<21))
do
    echo "$iterator"
    case $iterator in
	"4") echo "bad luck from China";;
	"9") echo "bad luck from Japan";;
	"17") echo "bad luck from Italy";;
    esac
    (( iterator++ ))
done
