#!/usr/bin/env bash
# This script is displaying the hours and minutes

hours=0
minutes=1

while ((hours<=12))
do
	echo "Hour: $hours"
	while ((minutes<=59))
	do
		echo "$minutes"
		((minutes++))
	done
	minutes=1
	((hours++))
done
