#!/usr/bin/env bash
pkill apache2
chmod 644 /etc/nginx/nginx.conf
chown -R nginx /etc/nginx/nginx.conf
sudo - nginx -c "sed -i -e 's/80/8080/g' /etc/nginx/sites-available/default"
sudo - nginx -c "service nginx restart" 2&> /dev/null
